spring:
  application:
    name:  task-manager
  datasource:
    hikari:
      connection-timeout:  5000
      maximum-pool-size:  2
    driver-class-name:  org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/taskmanager
    username:  postgres
    password:  1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    hibernate:
      ddl-auto:  update
